name: CI

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.21.1'

    - name: Tidy modules
      run: go mod tidy

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3

    - name: Turnstyle
      if: ${{ github.event_name == 'push' && github.ref == 'refs/head/trunk' }}
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Image
      run: docker build --file Dockerfile --tag microgopster:latest .

    - name: Push to GitHub
      if: ${{ github.repository == 'holedaemon/microgopster' && github.event_name == 'push' && github.ref == 'refs/heads/trunk' }}
      run: |
        echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker tag microgopster:latest ghcr.io/holedaemon/microgopster:latest
        docker push ghcr.io/holedaemon/microgopster:latest